services:
  api:
    build:
      context: ./src
      dockerfile: EchoHub.App/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      GitHub__Token: ${GITHUB_TOKEN:-}
    ports:
      - "${API_PORT:-8080}:8080"

  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT:-80}:80"
    depends_on:
      - api
